import type { LocalizedTerm } from "./localized";

/** LinkedIn Industry Codes V2. English labels are the official names. Portuguese and Spanish are shown in the interface. */
export const LINKEDIN_INDUSTRIES: readonly LocalizedTerm[] = [
  { en: "Abrasives and Nonmetallic Minerals Manufacturing", pt: "Fabricação de Abrasivos e Minerais Não-Metálicos", es: "Fabricación de abrasivos y minerales no metálicos" },
  { en: "Accessible Architecture and Design", pt: "Arquitetura e Design Acessíveis", es: "Arquitectura y diseño accesibles" },
  { en: "Accessible Hardware Manufacturing", pt: "Fabricação de hardware acessível", es: "Fabricación de hardware accesible" },
  { en: "Accommodation Services", pt: "Serviços de Acomodação", es: "Servicios de alojamiento" },
  { en: "Accounting", pt: "Contabilidade", es: "Contabilidad" },
  { en: "Administration of Justice", pt: "Administração da Justiça", es: "Administración de justicia" },
  { en: "Administrative and Support Services", pt: "Serviços Administrativos e de Suporte", es: "Servicios administrativos y de apoyo" },
  { en: "Advertising Services", pt: "Serviços de Publicidade", es: "Servicios de publicidad" },
  { en: "Agricultural Chemical Manufacturing", pt: "Fabricação de Produtos Químicos Agrícolas", es: "Fabricación de productos químicos agrícolas" },
  { en: "Agriculture, Construction, Mining Machinery Manufacturing", pt: "Fabricação de Maquinários de Agricultura, Construção e Mineração", es: "Fabricación de maquinaria agrícola, de construcción y minería" },
  { en: "Air, Water, and Waste Program Management", pt: "Gestão de programas de ar, água e resíduos", es: "Gestión de programas de aire, agua y residuos" },
  { en: "Airlines and Aviation", pt: "Companhias Aéreas e Aviação", es: "Aerolíneas y aviación" },
  { en: "Alternative Dispute Resolution", pt: "Resolução alternativa de conflitos", es: "Resolución alternativa de conflictos" },
  { en: "Alternative Fuel Vehicle Manufacturing", pt: "Fabricação de Veículos Motorizados de Combustível Alternativo", es: "Fabricación de vehículos de combustible alternativo" },
  { en: "Alternative Medicine", pt: "Medicina Alternativa", es: "Medicina alternativa" },
  { en: "Ambulance Services", pt: "Serviços de Ambulância", es: "Servicios de ambulancia" },
  { en: "Amusement Parks and Arcades", pt: "Parques de Diversão e Fliperamas", es: "Parques de atracciones y salones recreativos" },
  { en: "Animal Feed Manufacturing", pt: "Fabricação de Alimentos para Animais", es: "Fabricación de alimentos para animales" },
  { en: "Animation and Post-production", pt: "Animação e Pós-produção", es: "Animación y posproducción" },
  { en: "Apparel Manufacturing", pt: "Fabricação de Vestuário", es: "Fabricación de prendas de vestir" },
  { en: "Appliances, Electrical, and Electronics Manufacturing", pt: "Fabricação de Eletrodomésticos, Aparelhos Elétricos e Eletrônicos", es: "Fabricación de electrodomésticos, equipos eléctricos y electrónicos" },
  { en: "Architectural and Structural Metal Manufacturing", pt: "Fabricação de Metais Arquitetônicos e Estruturais", es: "Fabricación de metales arquitectónicos y estructurales" },
  { en: "Architecture and Planning", pt: "Arquitetura e Planejamento", es: "Arquitectura y planificación" },
  { en: "Armed Forces", pt: "Forças Armadas", es: "Fuerzas armadas" },
  { en: "Artificial Rubber and Synthetic Fiber Manufacturing", pt: "Fabricação de Borracha Artificial e Fibra Sintética", es: "Fabricación de caucho artificial y fibra sintética" },
  { en: "Artists and Writers", pt: "Artistas e Escritores", es: "Artistas y escritores" },
  { en: "Audio and Video Equipment Manufacturing", pt: "Fabricação de Equipamentos de Áudio e Vídeo", es: "Fabricación de equipos de audio y vídeo" },
  { en: "Automation Machinery Manufacturing", pt: "Fabricação de Maquinários de Automação", es: "Fabricación de maquinaria de automatización" },
  { en: "Aviation and Aerospace Component Manufacturing", pt: "Fabricação de componentes de aviação e aeroespaciais", es: "Fabricación de componentes de aviación y aeroespaciales" },
  { en: "Baked Goods Manufacturing", pt: "Fabricação de Produtos de Panificação", es: "Fabricación de productos de panadería" },
  { en: "Banking", pt: "Bancos", es: "Banca" },
  { en: "Bars, Taverns, and Nightclubs", pt: "Bares, tabernas e boates", es: "Bares, tabernas y discotecas" },
  { en: "Bed-and-Breakfasts, Hostels, Homestays", pt: "Pousadas, Albergues, Casas de Família", es: "Pensiones, albergues y alojamiento en casas" },
  { en: "Beverage Manufacturing", pt: "Fabricação de Bebidas", es: "Fabricación de bebidas" },
  { en: "Biomass Electric Power Generation", pt: "Geração de Energia Elétrica de Biomassa", es: "Generación de energía eléctrica con biomasa" },
  { en: "Biotechnology Research", pt: "Pesquisa de Biotecnologia", es: "Investigación en biotecnología" },
  { en: "Blockchain Services", pt: "Serviços de Blockchain", es: "Servicios de blockchain" },
  { en: "Blogs", pt: "Blogs", es: "Blogs" },
  { en: "Boilers, Tanks, and Shipping Container Manufacturing", pt: "Fabricação de Caldeiras, Tanques e Contêineres", es: "Fabricación de calderas, tanques y contenedores" },
  { en: "Book and Periodical Publishing", pt: "Publicação de Livros e Periódicos", es: "Edición de libros y publicaciones periódicas" },
  { en: "Book Publishing", pt: "Publicação de Livros", es: "Edición de libros" },
  { en: "Breweries", pt: "Cervejarias", es: "Cervecerías" },
  { en: "Broadcast Media Production and Distribution", pt: "Produção e Distribuição de Mídia de Transmissão", es: "Producción y distribución de medios de difusión" },
  { en: "Building Construction", pt: "Construção de Edifícios", es: "Construcción de edificios" },
  { en: "Building Equipment Contractors", pt: "Empreiteiros de Equipamentos de Construção", es: "Contratistas de equipamiento de edificios" },
  { en: "Building Finishing Contractors", pt: "Empreiteiros de Acabamento de Construção", es: "Contratistas de acabados de edificios" },
  { en: "Building Structure and Exterior Contractors", pt: "Empreiteiros de Estrutura e Exterior de Construção", es: "Contratistas de estructura y exterior de edificios" },
  { en: "Business Consulting and Services", pt: "Consultoria e Serviços de Negócios", es: "Consultoría y servicios empresariales" },
  { en: "Business Content", pt: "Conteúdo de negócios", es: "Contenido de negocios" },
  { en: "Business Intelligence Platforms", pt: "Plataformas de Inteligência de Negócios", es: "Plataformas de inteligencia de negocios" },
  { en: "Cable and Satellite Programming", pt: "Programação a cabo e por satélite", es: "Programación por cable y satélite" },
  { en: "Capital Markets", pt: "Mercado de Capitais", es: "Mercados de capitales" },
  { en: "Caterers", pt: "Buffet e catering", es: "Catering" },
  { en: "Chemical Manufacturing", pt: "Fabricação de Produtos Químicos", es: "Fabricación de productos químicos" },
  { en: "Chemical Raw Materials Manufacturing", pt: "Fabricação de Matérias-primas Químicas", es: "Fabricación de materias primas químicas" },
  { en: "Child Day Care Services", pt: "Serviços de Creche para Crianças", es: "Servicios de guardería" },
  { en: "Chiropractors", pt: "Quiropratas", es: "Quiroprácticos" },
  { en: "Circuses and Magic Shows", pt: "Circos e Shows de Mágica", es: "Circos y espectáculos de magia" },
  { en: "Civic and Social Organizations", pt: "Organizações Cívicas e Sociais", es: "Organizaciones cívicas y sociales" },
  { en: "Civil Engineering", pt: "Engenharia Civil", es: "Ingeniería civil" },
  { en: "Claims Adjusting, Actuarial Services", pt: "Regulação de Sinistros, Serviços Atuariais", es: "Ajuste de siniestros y servicios actuariales" },
  { en: "Clay and Refractory Products Manufacturing", pt: "Fabricação de Produtos de Argila e Refratários", es: "Fabricación de productos de arcilla y refractarios" },
  { en: "Climate Data and Analytics", pt: "Dados e Análises Climáticas", es: "Datos y analítica climática" },
  { en: "Climate Technology Product Manufacturing", pt: "Fabricação de produtos de tecnologia climática", es: "Fabricación de productos de tecnología climática" },
  { en: "Coal Mining", pt: "Mineração de Carvão", es: "Minería de carbón" },
  { en: "Collection Agencies", pt: "Agências de Cobrança", es: "Agencias de cobro" },
  { en: "Commercial and Industrial Equipment Rental", pt: "Aluguel de Equipamentos Comerciais e Industriais", es: "Alquiler de equipos comerciales e industriales" },
  { en: "Commercial and Industrial Machinery Maintenance", pt: "Manutenção de maquinário comercial e industrial", es: "Mantenimiento de maquinaria comercial e industrial" },
  { en: "Commercial and Service Industry Machinery Manufacturing", pt: "Fabricação de Maquinário da Indústria Comercial e de Serviços", es: "Fabricación de maquinaria para la industria comercial y de servicios" },
  { en: "Communications Equipment Manufacturing", pt: "Fabricação de Equipamentos de Comunicação", es: "Fabricación de equipos de comunicaciones" },
  { en: "Community Development and Urban Planning", pt: "Desenvolvimento Comunitário e Planejamento Urbano", es: "Desarrollo comunitario y planificación urbana" },
  { en: "Community Services", pt: "Serviços comunitários", es: "Servicios comunitarios" },
  { en: "Computer and Network Security", pt: "Segurança de Redes e Computadores", es: "Seguridad informática y de redes" },
  { en: "Computer Games", pt: "Jogos de Computador", es: "Videojuegos de ordenador" },
  { en: "Computer Hardware Manufacturing", pt: "Fabricação de Hardware de Computadores", es: "Fabricación de hardware informático" },
  { en: "Computer Networking Products", pt: "Produtos de Redes de Computadores", es: "Productos de redes informáticas" },
  { en: "Computers and Electronics Manufacturing", pt: "Fabricação de Computadores e Eletrônicos", es: "Fabricación de ordenadores y electrónica" },
  { en: "Conservation Programs", pt: "Programas de Conservação", es: "Programas de conservación" },
  { en: "Construction", pt: "Construção", es: "Construcción" },
  { en: "Construction Hardware Manufacturing", pt: "Fabricação de Ferragens para Construção", es: "Fabricación de herrajes para la construcción" },
  { en: "Consumer Goods Rental", pt: "Aluguel de Bens de Consumo", es: "Alquiler de bienes de consumo" },
  { en: "Consumer Services", pt: "Serviços ao Consumidor", es: "Servicios al consumidor" },
  { en: "Correctional Institutions", pt: "Instituições Correcionais", es: "Instituciones penitenciarias" },
  { en: "Cosmetology and Barber Schools", pt: "Escolas de Cosmetologia e Barbearia", es: "Escuelas de cosmetología y barbería" },
  { en: "Courts of Law", pt: "Tribunais de Justiça", es: "Tribunales" },
  { en: "Credit Intermediation", pt: "Intermediação de Crédito", es: "Intermediación de crédito" },
  { en: "Cutlery and Handtool Manufacturing", pt: "Fabricação de Cutelaria e Ferramentas Manuais", es: "Fabricación de cuchillería y herramientas manuales" },
  { en: "Dairy Product Manufacturing", pt: "Fabricação de Produtos Lácteos", es: "Fabricación de productos lácteos" },
  { en: "Dance Companies", pt: "Companhias de Dança", es: "Compañías de danza" },
  { en: "Data Infrastructure and Analytics", pt: "Infraestrutura e Análise de Dados", es: "Infraestructura y analítica de datos" },
  { en: "Data Security Software Products", pt: "Produtos de Software de Segurança de Dados", es: "Productos de software de seguridad de datos" },
  { en: "Defense and Space Manufacturing", pt: "Fabricação Espacial e de Defesa", es: "Fabricación para defensa y espacio" },
  { en: "Dentists", pt: "Dentistas", es: "Dentistas" },
  { en: "Design Services", pt: "Serviços de Design", es: "Servicios de diseño" },
  { en: "Desktop Computing Software Products", pt: "Produtos de Software de Computação em Desktop", es: "Productos de software de escritorio" },
  { en: "Digital Accessibility Services", pt: "Serviços de Acessibilidade Digital", es: "Servicios de accesibilidad digital" },
  { en: "Distilleries", pt: "Destilarias", es: "Destilerías" },
  { en: "E-Learning Providers", pt: "Provedores de E-learning", es: "Proveedores de formación en línea" },
  { en: "Economic Programs", pt: "Programas Econômicos", es: "Programas económicos" },
  { en: "Education", pt: "Educação", es: "Educación" },
  { en: "Education Administration Programs", pt: "Programas de Administração de Educação", es: "Programas de administración educativa" },
  { en: "Electric Lighting Equipment Manufacturing", pt: "Fabricação de Equipamentos de Iluminação Elétrica", es: "Fabricación de equipos de iluminación eléctrica" },
  { en: "Electric Power Generation", pt: "Geração de Energia Elétrica", es: "Generación de energía eléctrica" },
  { en: "Electric Power Transmission, Control, and Distribution", pt: "Transmissão, Controle e Distribuição de Energia Elétrica", es: "Transmisión, control y distribución de energía eléctrica" },
  { en: "Electrical Equipment Manufacturing", pt: "Fabricação de Equipamentos Elétricos", es: "Fabricación de equipos eléctricos" },
  { en: "Electronic and Precision Equipment Maintenance", pt: "Manutenção de Equipamentos Eletrônicos e de Precisão", es: "Mantenimiento de equipos electrónicos y de precisión" },
  { en: "Embedded Software Products", pt: "Produtos de Software Embarcados", es: "Productos de software embebido" },
  { en: "Emergency and Relief Services", pt: "Serviços de Emergência e Socorro", es: "Servicios de emergencia y socorro" },
  { en: "Engineering Services", pt: "Serviços de Engenharia", es: "Servicios de ingeniería" },
  { en: "Engines and Power Transmission Equipment Manufacturing", pt: "Fabricação de Equipamentos para Motores e Transmissão de Energia", es: "Fabricación de motores y equipos de transmisión de energía" },
  { en: "Entertainment Providers", pt: "Provedores de Entretenimento", es: "Proveedores de entretenimiento" },
  { en: "Environmental Quality Programs", pt: "Programas de Qualidade Ambiental", es: "Programas de calidad ambiental" },
  { en: "Environmental Services", pt: "Serviços Ambientais", es: "Servicios ambientales" },
  { en: "Equipment Rental Services", pt: "Serviços de Aluguel de Equipamentos", es: "Servicios de alquiler de equipos" },
  { en: "Events Services", pt: "Serviços de Eventos", es: "Servicios para eventos" },
  { en: "Executive Offices", pt: "Escritórios Executivos", es: "Oficinas ejecutivas" },
  { en: "Executive Search Services", pt: "Recrutamento executivo", es: "Búsqueda de ejecutivos" },
  { en: "Fabricated Metal Products", pt: "Produtos Metálicos Fabricados", es: "Productos metálicos fabricados" },
  { en: "Facilities Services", pt: "Serviços de Instalações", es: "Servicios de instalaciones" },
  { en: "Family Planning Centers", pt: "Centros de Planejamento Familiar", es: "Centros de planificación familiar" },
  { en: "Farming", pt: "Agricultura", es: "Agricultura" },
  { en: "Farming, Ranching, Forestry", pt: "Agricultura, Pecuária, Silvicultura", es: "Agricultura, ganadería y silvicultura" },
  { en: "Fashion Accessories Manufacturing", pt: "Fabricação de acessórios de moda", es: "Fabricación de accesorios de moda" },
  { en: "Financial Services", pt: "Serviços Financeiros", es: "Servicios financieros" },
  { en: "Fine Arts Schools", pt: "Escolas de Belas Artes", es: "Escuelas de bellas artes" },
  { en: "Fire Protection", pt: "Proteção contra Incêndios", es: "Protección contra incendios" },
  { en: "Fisheries", pt: "Pesca", es: "Pesca" },
  { en: "Flight Training", pt: "Treinamento de Voo", es: "Formación de vuelo" },
  { en: "Food and Beverage Manufacturing", pt: "Fabricação de Alimentos e Bebidas", es: "Fabricación de alimentos y bebidas" },
  { en: "Food and Beverage Retail", pt: "Varejo de Alimentos e Bebidas", es: "Venta minorista de alimentos y bebidas" },
  { en: "Food and Beverage Services", pt: "Serviços de Alimentos e Bebidas", es: "Servicios de alimentos y bebidas" },
  { en: "Footwear and Leather Goods Repair", pt: "Reparação de Calçados e Artigos de Couro", es: "Reparación de calzado y artículos de cuero" },
  { en: "Footwear Manufacturing", pt: "Fabricação de Calçados", es: "Fabricación de calzado" },
  { en: "Forestry and Logging", pt: "Silvicultura e Madeireiras", es: "Silvicultura y explotación forestal" },
  { en: "Fossil Fuel Electric Power Generation", pt: "Geração de energia elétrica de Combustível Fóssil", es: "Generación de energía eléctrica con combustibles fósiles" },
  { en: "Freight and Package Transportation", pt: "Transporte de Frete e Pacotes", es: "Transporte de carga y paquetería" },
  { en: "Fruit and Vegetable Preserves Manufacturing", pt: "Fabricação de Conservas de Frutas e Vegetais", es: "Fabricación de conservas de frutas y verduras" },
  { en: "Fuel Cell Manufacturing", pt: "Fabricação de Células de Combustível", es: "Fabricación de pilas de combustible" },
  { en: "Fundraising", pt: "Captação de Recursos", es: "Captación de fondos" },
  { en: "Funds and Trusts", pt: "Fundos e Trusts", es: "Fondos y fideicomisos" },
  { en: "Furniture and Home Furnishings Manufacturing", pt: "Fabricação de Móveis e Artigos de Decoração", es: "Fabricación de muebles y artículos para el hogar" },
  { en: "Gambling Facilities and Casinos", pt: "Instalações de Jogos de Azar e Cassinos", es: "Instalaciones de juego y casinos" },
  { en: "Geothermal Electric Power Generation", pt: "Geração de Energia Elétrica Geotérmica", es: "Generación de energía eléctrica geotérmica" },
  { en: "Glass Product Manufacturing", pt: "Fabricação de Produtos de Vidro", es: "Fabricación de productos de vidrio" },
  { en: "Glass, Ceramics and Concrete Manufacturing", pt: "Fabricação de Vidro, Cerâmica e Concreto", es: "Fabricación de vidrio, cerámica y hormigón" },
  { en: "Golf Courses and Country Clubs", pt: "Campos de Golfe e Clubes de Campo", es: "Campos de golf y clubes de campo" },
  { en: "Government Administration", pt: "Administração Governamental", es: "Administración pública" },
  { en: "Government Relations Services", pt: "Serviços de Relações Governamentais", es: "Servicios de relaciones con el gobierno" },
  { en: "Graphic Design", pt: "Design Gráfico", es: "Diseño gráfico" },
  { en: "Ground Passenger Transportation", pt: "Transporte Terrestre de Passageiros", es: "Transporte terrestre de pasajeros" },
  { en: "Health and Human Services", pt: "Saúde e Serviços Humanos", es: "Salud y servicios humanos" },
  { en: "Higher Education", pt: "Ensino Superior", es: "Educación superior" },
  { en: "Highway, Street, and Bridge Construction", pt: "Construção de Rodovias, Ruas e Pontes", es: "Construcción de carreteras, calles y puentes" },
  { en: "Historical Sites", pt: "Locais Históricos", es: "Sitios históricos" },
  { en: "Holding Companies", pt: "Holdings", es: "Sociedades holding" },
  { en: "Home Health Care Services", pt: "Serviços de saúde domiciliar", es: "Servicios de atención sanitaria a domicilio" },
  { en: "Horticulture", pt: "Horticultura", es: "Horticultura" },
  { en: "Hospitality", pt: "Hotelaria", es: "Hostelería" },
  { en: "Hospitals", pt: "Hospitais", es: "Hospitales" },
  { en: "Hospitals and Health Care", pt: "Hospitais e Assistência Médica", es: "Hospitales y atención sanitaria" },
  { en: "Hotels and Motels", pt: "Hotéis e Motéis", es: "Hoteles y moteles" },
  { en: "Household and Institutional Furniture Manufacturing", pt: "Fabricação de Móveis Domésticos e Institucionais", es: "Fabricación de muebles domésticos e institucionales" },
  { en: "Household Appliance Manufacturing", pt: "Fabricação de Eletrodomésticos", es: "Fabricación de electrodomésticos" },
  { en: "Household Services", pt: "Serviços Domésticos", es: "Servicios domésticos" },
  { en: "Housing and Community Development", pt: "Habitação e Desenvolvimento Comunitário", es: "Vivienda y desarrollo comunitario" },
  { en: "Housing Programs", pt: "Programas Habitacionais", es: "Programas de vivienda" },
  { en: "Human Resources Services", pt: "Serviços de Recursos Humanos", es: "Servicios de recursos humanos" },
  { en: "HVAC and Refrigeration Equipment Manufacturing", pt: "Fabricação de Equipamentos HVAC e de Refrigeração", es: "Fabricación de equipos de climatización y refrigeración" },
  { en: "Hydroelectric Power Generation", pt: "Geração de Energia Hidrelétrica", es: "Generación de energía hidroeléctrica" },
  { en: "Individual and Family Services", pt: "Serviços Individuais e Familiares", es: "Servicios para personas y familias" },
  { en: "Industrial Machinery Manufacturing", pt: "Fabricação de Maquinários Industriais", es: "Fabricación de maquinaria industrial" },
  { en: "Industry Associations", pt: "Associações da Indústria", es: "Asociaciones del sector" },
  { en: "Information Services", pt: "Serviços de Informação", es: "Servicios de información" },
  { en: "Insurance", pt: "Seguros", es: "Seguros" },
  { en: "Insurance Agencies and Brokerages", pt: "Agências de Seguros e Corretoras", es: "Agencias y corredurías de seguros" },
  { en: "Insurance and Employee Benefit Funds", pt: "Seguros e Fundos de Benefícios de Funcionários", es: "Seguros y fondos de prestaciones para empleados" },
  { en: "Insurance Carriers", pt: "Seguradoras", es: "Aseguradoras" },
  { en: "Interior Design", pt: "Design de Interiores", es: "Diseño de interiores" },
  { en: "International Affairs", pt: "Assuntos Internacionais", es: "Asuntos internacionales" },
  { en: "International Trade and Development", pt: "Comércio e Desenvolvimento Internacional", es: "Comercio internacional y desarrollo" },
  { en: "Internet Marketplace Platforms", pt: "Plataformas de Marketplace na Internet", es: "Plataformas de mercado en internet" },
  { en: "Internet News", pt: "Notícias na Internet", es: "Noticias en internet" },
  { en: "Internet Publishing", pt: "Publicação na Internet", es: "Edición en internet" },
  { en: "Interurban and Rural Bus Services", pt: "Serviços de Ônibus Interurbanos e Rurais", es: "Servicios de autobús interurbano y rural" },
  { en: "Investment Advice", pt: "Consultoria de Investimentos", es: "Asesoramiento de inversiones" },
  { en: "Investment Banking", pt: "Banco de investimento", es: "Banca de inversión" },
  { en: "Investment Management", pt: "Gestão de Investimentos", es: "Gestión de inversiones" },
  { en: "IT Services and IT Consulting", pt: "Serviços de TI e Consultoria de TI", es: "Servicios de TI y consultoría de TI" },
  { en: "IT System Custom Software Development", pt: "Desenvolvimento de software sob medida para sistemas de TI", es: "Desarrollo de software a medida para sistemas de TI" },
  { en: "IT System Data Services", pt: "Serviços de Dados do Sistema de TI", es: "Servicios de datos de sistemas de TI" },
  { en: "IT System Design Services", pt: "Serviços de Design de Sistemas de TI", es: "Servicios de diseño de sistemas de TI" },
  { en: "IT System Installation and Disposal", pt: "Instalação e Descarte de Sistemas de TI", es: "Instalación y retirada de sistemas de TI" },
  { en: "IT System Operations and Maintenance", pt: "Operação e Manutenção de Sistemas de TI", es: "Operación y mantenimiento de sistemas de TI" },
  { en: "IT System Testing and Evaluation", pt: "Testes e Avaliações de Sistemas de TI", es: "Pruebas y evaluación de sistemas de TI" },
  { en: "IT System Training and Support", pt: "Treinamento e Suporte para Sistemas de TI", es: "Formación y soporte de sistemas de TI" },
  { en: "Janitorial Services", pt: "Serviços de Zeladoria", es: "Servicios de limpieza" },
  { en: "Landscaping Services", pt: "Serviços de Paisagismo", es: "Servicios de paisajismo" },
  { en: "Language Schools", pt: "Escolas de Idiomas", es: "Escuelas de idiomas" },
  { en: "Laundry and Drycleaning Services", pt: "Lavanderia e limpeza a seco", es: "Lavandería y tintorería" },
  { en: "Law Enforcement", pt: "Policiamento", es: "Fuerzas de seguridad" },
  { en: "Law Practice", pt: "Advocacia", es: "Ejercicio de la abogacía" },
  { en: "Leasing Non-residential Real Estate", pt: "Locação de imóveis não residenciais", es: "Arrendamiento de inmuebles no residenciales" },
  { en: "Leasing Residential Real Estate", pt: "Locação de imóveis residenciais", es: "Arrendamiento de inmuebles residenciales" },
  { en: "Leather Product Manufacturing", pt: "Fabricação de Produtos de Couro", es: "Fabricación de productos de cuero" },
  { en: "Legal Services", pt: "Serviços Jurídicos", es: "Servicios jurídicos" },
  { en: "Legislative Offices", pt: "Escritórios Legislativos", es: "Oficinas legislativas" },
  { en: "Libraries", pt: "Bibliotecas", es: "Bibliotecas" },
  { en: "Lime and Gypsum Products Manufacturing", pt: "Fabricação de Produtos de Cal e Gesso", es: "Fabricación de productos de cal y yeso" },
  { en: "Loan Brokers", pt: "Corretores de Empréstimos", es: "Intermediarios de préstamos" },
  { en: "Machinery Manufacturing", pt: "Fabricação de Maquinários", es: "Fabricación de maquinaria" },
  { en: "Magnetic and Optical Media Manufacturing", pt: "Fabricação de Mídia Magnética e Óptica", es: "Fabricación de soportes magnéticos y ópticos" },
  { en: "Manufacturing", pt: "Fabricação", es: "Fabricación" },
  { en: "Maritime Transportation", pt: "Transporte Marítimo", es: "Transporte marítimo" },
  { en: "Market Research", pt: "Pesquisa de Mercado", es: "Investigación de mercado" },
  { en: "Marketing Services", pt: "Serviços de Marketing", es: "Servicios de marketing" },
  { en: "Mattress and Blinds Manufacturing", pt: "Fabricação de Colchões e Persianas", es: "Fabricación de colchones y persianas" },
  { en: "Measuring and Control Instrument Manufacturing", pt: "Fabricação de Instrumentos de Medição e Controle", es: "Fabricación de instrumentos de medición y control" },
  { en: "Meat Products Manufacturing", pt: "Fabricação de Produtos de Carne", es: "Fabricación de productos cárnicos" },
  { en: "Media & Telecommunications", pt: "Mídia e Telecomunicações", es: "Medios y telecomunicaciones" },
  { en: "Media Production", pt: "Produção de mídia", es: "Producción de medios" },
  { en: "Medical and Diagnostic Laboratories", pt: "Laboratórios Médicos e Diagnósticos", es: "Laboratorios médicos y de diagnóstico" },
  { en: "Medical Equipment Manufacturing", pt: "Fabricação de Equipamentos Médicos", es: "Fabricación de equipos médicos" },
  { en: "Medical Practices", pt: "Consultórios médicos", es: "Consultorios médicos" },
  { en: "Mental Health Care", pt: "Cuidados de Saúde Mental", es: "Atención de salud mental" },
  { en: "Metal Ore Mining", pt: "Mineração de Minério de Metal", es: "Minería de minerales metálicos" },
  { en: "Metal Treatments", pt: "Tratamentos de Metais", es: "Tratamientos de metales" },
  { en: "Metal Valve, Ball, and Roller Manufacturing", pt: "Fabricação de Válvulas, Bolas e Rolos de Metal", es: "Fabricación de válvulas, bolas y rodillos metálicos" },
  { en: "Metalworking Machinery Manufacturing", pt: "Fabricação de Maquinários para Metalurgia", es: "Fabricación de maquinaria para el trabajo del metal" },
  { en: "Military and International Affairs", pt: "Assuntos Militares e Internacionais", es: "Asuntos militares e internacionales" },
  { en: "Mining", pt: "Mineração", es: "Minería" },
  { en: "Mobile Computing Software Products", pt: "Produtos de Software de Computação Móvel", es: "Productos de software de computación móvil" },
  { en: "Mobile Food Services", pt: "Serviços de Alimentação Móvel", es: "Servicios de comida móvil" },
  { en: "Mobile Gaming Apps", pt: "Aplicativos de jogos para celular", es: "Aplicaciones de juegos para móvil" },
  { en: "Motor Vehicle Manufacturing", pt: "Fabricação de Veículos Motorizados", es: "Fabricación de vehículos de motor" },
  { en: "Motor Vehicle Parts Manufacturing", pt: "Fabricação de Peças de Veículos Motorizados", es: "Fabricación de piezas de vehículos de motor" },
  { en: "Movies and Sound Recording", pt: "Filmes e Gravação de Som", es: "Cine y grabación de sonido" },
  { en: "Movies, Videos and Sound", pt: "Filmes, Vídeos e Som", es: "Cine, vídeo y sonido" },
  { en: "Museums", pt: "Museus", es: "Museos" },
  { en: "Museums, Historical Sites, and Zoos", pt: "Museus, Locais Históricos e Zoológicos", es: "Museos, sitios históricos y zoológicos" },
  { en: "Musicians", pt: "Músicos", es: "Músicos" },
  { en: "Nanotechnology Research", pt: "Pesquisa de Nanotecnologia", es: "Investigación en nanotecnología" },
  { en: "Natural Gas Distribution", pt: "Distribuição de Gás Natural", es: "Distribución de gas natural" },
  { en: "Natural Gas Extraction", pt: "Extração de Gás Natural", es: "Extracción de gas natural" },
  { en: "Newspaper Publishing", pt: "Publicação de Jornais", es: "Edición de periódicos" },
  { en: "Non-profit Organizations", pt: "Organizações Sem Fins Lucrativos", es: "Organizaciones sin fines de lucro" },
  { en: "Nonmetallic Mineral Mining", pt: "Mineração Mineral Não-Metálica", es: "Minería de minerales no metálicos" },
  { en: "Nonresidential Building Construction", pt: "Construção de edifícios não residenciais", es: "Construcción de edificios no residenciales" },
  { en: "Nuclear Electric Power Generation", pt: "Geração de Energia Elétrica Nuclear", es: "Generación de energía eléctrica nuclear" },
  { en: "Nursing Homes and Residential Care Facilities", pt: "Casas de repouso e instituições de cuidado residencial", es: "Residencias de ancianos y centros de cuidado residencial" },
  { en: "Office Administration", pt: "Administração de Escritórios", es: "Administración de oficinas" },
  { en: "Office Furniture and Fixtures Manufacturing", pt: "Fabricação de Móveis e utensílios de Escritório", es: "Fabricación de muebles y accesorios de oficina" },
  { en: "Oil and Coal Product Manufacturing", pt: "Fabricação de Produtos Petrolíferos e de Carvão", es: "Fabricación de productos de petróleo y carbón" },
  { en: "Oil and Gas", pt: "Petróleo e Gás", es: "Petróleo y gas" },
  { en: "Oil Extraction", pt: "Extração de Petróleo", es: "Extracción de petróleo" },
  { en: "Oil, Gas, and Mining", pt: "Petróleo, Gás e Mineração", es: "Petróleo, gas y minería" },
  { en: "Online and Mail Order Retail", pt: "Varejo Online e por Correio", es: "Venta minorista en línea y por correo" },
  { en: "Online Audio and Video Media", pt: "Mídia de Áudio e Vídeo Online", es: "Medios de audio y vídeo en línea" },
  { en: "Operations Consulting", pt: "Consultoria de Operações", es: "Consultoría de operaciones" },
  { en: "Optometrists", pt: "Optometristas", es: "Optometristas" },
  { en: "Outpatient Care Centers", pt: "Centros de Atendimento Ambulatorial", es: "Centros de atención ambulatoria" },
  { en: "Outsourcing and Offshoring Consulting", pt: "Consultoria de Terceirização e Offshoring", es: "Consultoría de externalización y deslocalización" },
  { en: "Packaging and Containers Manufacturing", pt: "Fabricação de Embalagens e Recipientes", es: "Fabricación de envases y contenedores" },
  { en: "Paint, Coating, and Adhesive Manufacturing", pt: "Fabricação de tintas, revestimentos e adesivos", es: "Fabricación de pinturas, recubrimientos y adhesivos" },
  { en: "Paper and Forest Product Manufacturing", pt: "Fabricação de Papel e Produtos Florestais", es: "Fabricación de papel y productos forestales" },
  { en: "Pension Funds", pt: "Fundos de Pensão", es: "Fondos de pensiones" },
  { en: "Performing Arts", pt: "Artes Cênicas", es: "Artes escénicas" },
  { en: "Performing Arts and Spectator Sports", pt: "Artes cênicas e esportes para espectadores", es: "Artes escénicas y deportes para espectadores" },
  { en: "Periodical Publishing", pt: "Publicação de Periódicos", es: "Edición de publicaciones periódicas" },
  { en: "Personal and Laundry Services", pt: "Serviços Pessoais e de Lavanderia", es: "Servicios personales y de lavandería" },
  { en: "Personal Care Product Manufacturing", pt: "Fabricação de Produtos para Cuidados Pessoais", es: "Fabricación de productos de cuidado personal" },
  { en: "Personal Care Services", pt: "Serviços de Cuidados Pessoais", es: "Servicios de cuidado personal" },
  { en: "Pet Services", pt: "Serviços para Animais de Estimação", es: "Servicios para mascotas" },
  { en: "Pharmaceutical Manufacturing", pt: "Fabricação Farmacêutica", es: "Fabricación de productos farmacéuticos" },
  { en: "Philanthropic Fundraising Services", pt: "Serviços de Captação de Recursos Filantrópicos", es: "Servicios de captación de fondos filantrópicos" },
  { en: "Photography", pt: "Fotografia", es: "Fotografía" },
  { en: "Physical, Occupational and Speech Therapists", pt: "Terapeutas Físicos, Ocupacionais e Fonoaudiólogos", es: "Fisioterapeutas, terapeutas ocupacionales y logopedas" },
  { en: "Physicians", pt: "Médicos", es: "Médicos" },
  { en: "Pipeline Transportation", pt: "Transporte por Dutos", es: "Transporte por tuberías" },
  { en: "Plastics and Rubber Product Manufacturing", pt: "Fabricação de Produtos de Plástico e Borracha", es: "Fabricación de productos de plástico y caucho" },
  { en: "Plastics Manufacturing", pt: "Fabricação de Plásticos", es: "Fabricación de plásticos" },
  { en: "Political Organizations", pt: "Organizações Políticas", es: "Organizaciones políticas" },
  { en: "Postal Services", pt: "Serviços Postais", es: "Servicios postales" },
  { en: "Primary and Secondary Education", pt: "Ensino fundamental e médio", es: "Educación primaria y secundaria" },
  { en: "Primary Metal Manufacturing", pt: "Fabricação de Metais Primários", es: "Fabricación de metales primarios" },
  { en: "Printing Services", pt: "Serviços de Impressão", es: "Servicios de impresión" },
  { en: "Professional Organizations", pt: "Organizações Profissionais", es: "Organizaciones profesionales" },
  { en: "Professional Services", pt: "Serviços Profissionais", es: "Servicios profesionales" },
  { en: "Professional Training and Coaching", pt: "Treinamento Profissional e Coaching", es: "Formación profesional y coaching" },
  { en: "Public Assistance Programs", pt: "Programas de Assistência Pública", es: "Programas de asistencia pública" },
  { en: "Public Health", pt: "Saúde Pública", es: "Salud pública" },
  { en: "Public Policy Offices", pt: "Escritórios de Política Pública", es: "Oficinas de política pública" },
  { en: "Public Relations and Communications Services", pt: "Serviços de Relações Públicas e Comunicações", es: "Servicios de relaciones públicas y comunicación" },
  { en: "Public Safety", pt: "Segurança Pública", es: "Seguridad pública" },
  { en: "Racetracks", pt: "Pistas de corrida", es: "Circuitos de carreras" },
  { en: "Radio and Television Broadcasting", pt: "Transmissão de Rádio e Televisão", es: "Radiodifusión y televisión" },
  { en: "Rail Transportation", pt: "Transporte Ferroviário", es: "Transporte ferroviario" },
  { en: "Railroad Equipment Manufacturing", pt: "Fabricação de Equipamentos Ferroviários", es: "Fabricación de equipos ferroviarios" },
  { en: "Ranching", pt: "Pecuária", es: "Ganadería" },
  { en: "Ranching and Fisheries", pt: "Pecuária e Pesca", es: "Ganadería y pesca" },
  { en: "Real Estate", pt: "Imóveis", es: "Bienes raíces" },
  { en: "Real Estate Agents and Brokers", pt: "Agentes Imobiliários e Corretores", es: "Agentes y corredores inmobiliarios" },
  { en: "Real Estate and Equipment Rental Services", pt: "Serviços Imobiliários e de Aluguel de Equipamentos", es: "Servicios inmobiliarios y de alquiler de equipos" },
  { en: "Recreational Facilities", pt: "Instalações Recreativas", es: "Instalaciones recreativas" },
  { en: "Regenerative Design", pt: "Design Regenerativo", es: "Diseño regenerativo" },
  { en: "Religious Institutions", pt: "Instituições Religiosas", es: "Instituciones religiosas" },
  { en: "Renewable Energy Equipment Manufacturing", pt: "Fabricação de Equipamentos de Energia Renovável", es: "Fabricación de equipos de energía renovable" },
  { en: "Renewable Energy Power Generation", pt: "Geração de Energia Renovável", es: "Generación de energía renovable" },
  { en: "Renewable Energy Semiconductor Manufacturing", pt: "Fabricação de Semicondutores de Energia Renovável", es: "Fabricación de semiconductores para energía renovable" },
  { en: "Repair and Maintenance", pt: "Reparo e Manutenção", es: "Reparación y mantenimiento" },
  { en: "Research Services", pt: "Serviços de Pesquisa", es: "Servicios de investigación" },
  { en: "Residential Building Construction", pt: "Construção de edifícios residenciais", es: "Construcción de edificios residenciales" },
  { en: "Restaurants", pt: "Restaurantes", es: "Restaurantes" },
  { en: "Retail", pt: "Varejo", es: "Comercio minorista" },
  { en: "Retail Apparel and Fashion", pt: "Varejo de vestuário e moda", es: "Comercio minorista de ropa y moda" },
  { en: "Retail Appliances, Electrical, and Electronic Equipment", pt: "Varejo de Eletrodomésticos, Equipamentos Elétricos e Eletrônicos", es: "Comercio minorista de electrodomésticos y equipos eléctricos y electrónicos" },
  { en: "Retail Art Dealers", pt: "Varejo de galerias e marchands", es: "Comercio minorista de arte" },
  { en: "Retail Art Supplies", pt: "Varejo de Materiais de Arte", es: "Comercio minorista de materiales de arte" },
  { en: "Retail Books and Printed News", pt: "Varejo de Livros e Notícias Impressas", es: "Comercio minorista de libros y prensa impresa" },
  { en: "Retail Building Materials and Garden Equipment", pt: "Varejo de Materiais de Construção e Equipamentos de Jardim", es: "Comercio minorista de materiales de construcción y jardinería" },
  { en: "Retail Florists", pt: "Floriculturas", es: "Floristerías" },
  { en: "Retail Furniture and Home Furnishings", pt: "Varejo de Móveis e Artigos de Decoração", es: "Comercio minorista de muebles y artículos para el hogar" },
  { en: "Retail Gasoline", pt: "Varejo de Gasolina", es: "Comercio minorista de gasolina" },
  { en: "Retail Groceries", pt: "Varejo de mercearias", es: "Comercio minorista de alimentación" },
  { en: "Retail Health and Personal Care Products", pt: "Varejo de Produtos de Saúde e Cuidados Pessoais", es: "Comercio minorista de productos de salud y cuidado personal" },
  { en: "Retail Luxury Goods and Jewelry", pt: "Varejo de Artigos de Luxo e Jóias", es: "Comercio minorista de artículos de lujo y joyería" },
  { en: "Retail Motor Vehicles", pt: "Varejo de Veículos Motorizados", es: "Comercio minorista de vehículos de motor" },
  { en: "Retail Musical Instruments", pt: "Varejo de Instrumentos Musicais", es: "Comercio minorista de instrumentos musicales" },
  { en: "Retail Office Equipment", pt: "Varejo de Equipamentos de Escritório", es: "Comercio minorista de equipos de oficina" },
  { en: "Retail Office Supplies and Gifts", pt: "Varejo de Artigos de Escritório e Presentes", es: "Comercio minorista de material de oficina y regalos" },
  { en: "Retail Pharmacies", pt: "Farmácias", es: "Farmacias" },
  { en: "Retail Recyclable Materials & Used Merchandise", pt: "Varejo de Materiais Recicláveis e Mercadorias Usadas", es: "Comercio minorista de materiales reciclables y artículos usados" },
  { en: "Reupholstery and Furniture Repair", pt: "Reestofamento e Reparo de Móveis", es: "Retapizado y reparación de muebles" },
  { en: "Robot Manufacturing", pt: "Fabricação de Robôs", es: "Fabricación de robots" },
  { en: "Robotics Engineering", pt: "Engenharia de Robótica", es: "Ingeniería robótica" },
  { en: "Rubber Products Manufacturing", pt: "Fabricação de Produtos de Borracha", es: "Fabricación de productos de caucho" },
  { en: "Satellite Telecommunications", pt: "Telecomunicações de Satélite", es: "Telecomunicaciones por satélite" },
  { en: "Savings Institutions", pt: "Instituições de Poupança", es: "Entidades de ahorro" },
  { en: "School and Employee Bus Services", pt: "Serviços de Ônibus Escolares e de Funcionários", es: "Servicios de autobús escolar y de personal" },
  { en: "Seafood Product Manufacturing", pt: "Fabricação de Produtos de Frutos do Mar", es: "Fabricación de productos del mar" },
  { en: "Secretarial Schools", pt: "Escolas de Secretariado", es: "Escuelas de secretariado" },
  { en: "Securities and Commodity Exchanges", pt: "Bolsa de Valores e Commodities", es: "Bolsas de valores y de materias primas" },
  { en: "Security and Investigations", pt: "Segurança e Investigações", es: "Seguridad e investigaciones" },
  { en: "Security Guards and Patrol Services", pt: "Serviços de vigilância e patrulha", es: "Servicios de vigilancia y patrulla" },
  { en: "Security Systems Services", pt: "Serviços de Sistemas de Segurança", es: "Servicios de sistemas de seguridad" },
  { en: "Semiconductor Manufacturing", pt: "Fabricação de Semicondutores", es: "Fabricación de semiconductores" },
  { en: "Services for Renewable Energy", pt: "Serviços para Energia Renovável", es: "Servicios para energía renovable" },
  { en: "Services for the Elderly and Disabled", pt: "Serviços para idosos e pessoas com deficiência", es: "Servicios para personas mayores y con discapacidad" },
  { en: "Sheet Music Publishing", pt: "Publicação de Partituras", es: "Edición de partituras" },
  { en: "Shipbuilding", pt: "Construção Naval", es: "Construcción naval" },
  { en: "Shuttles and Special Needs Transportation Services", pt: "Transporte especial e para pessoas com necessidades específicas", es: "Lanzaderas y transporte para necesidades especiales" },
  { en: "Sightseeing Transportation", pt: "Transporte Turístico", es: "Transporte turístico" },
  { en: "Skiing Facilities", pt: "Instalações de Esqui", es: "Instalaciones de esquí" },
  { en: "Smart Meter Manufacturing", pt: "Fabricação de Medidores Inteligentes", es: "Fabricación de contadores inteligentes" },
  { en: "Soap and Cleaning Product Manufacturing", pt: "Fabricação de Sabão e Produtos de Limpeza", es: "Fabricación de jabón y productos de limpieza" },
  { en: "Social Networking Platforms", pt: "Plataformas de Redes Sociais", es: "Plataformas de redes sociales" },
  { en: "Software Development", pt: "Desenvolvimento de Software", es: "Desarrollo de software" },
  { en: "Solar Electric Power Generation", pt: "Geração de Energia Elétrica Solar", es: "Generación de energía eléctrica solar" },
  { en: "Sound Recording", pt: "Gravação de Som", es: "Grabación de sonido" },
  { en: "Space Research and Technology", pt: "Pesquisa e Tecnologia Espaciais", es: "Investigación y tecnología espacial" },
  { en: "Specialty Trade Contractors", pt: "Empreiteiros de ofícios especializados", es: "Contratistas de oficios especializados" },
  { en: "Spectator Sports", pt: "Esportes para espectadores", es: "Deportes para espectadores" },
  { en: "Sporting Goods Manufacturing", pt: "Fabricação de Produtos Esportivos", es: "Fabricación de artículos deportivos" },
  { en: "Sports and Recreation Instruction", pt: "Instrução de Esportes e Recreação", es: "Enseñanza de deportes y recreación" },
  { en: "Sports Teams and Clubs", pt: "Equipes Esportivas e Clubes", es: "Equipos y clubes deportivos" },
  { en: "Spring and Wire Product Manufacturing", pt: "Fabricação de Produtos de Mola e Arame", es: "Fabricación de productos de muelles y alambre" },
  { en: "Staffing and Recruiting", pt: "Recrutamento e Seleção de Pessoal", es: "Selección y reclutamiento de personal" },
  { en: "Steam and Air-Conditioning Supply", pt: "Fornecimento de Vapor e Ar Condicionado", es: "Suministro de vapor y aire acondicionado" },
  { en: "Strategic Management Services", pt: "Serviços de gestão estratégica", es: "Servicios de gestión estratégica" },
  { en: "Subdivision of Land", pt: "Subdivisão de Terras", es: "Parcelación de terrenos" },
  { en: "Sugar and Confectionery Product Manufacturing", pt: "Fabricação de Produtos de Açúcar e Confeitaria", es: "Fabricación de azúcar y productos de confitería" },
  { en: "Surveying and Mapping Services", pt: "Serviços de Levantamento e Mapeamento", es: "Servicios de topografía y cartografía" },
  { en: "Taxi and Limousine Services", pt: "Serviços de Táxi e Limusine", es: "Servicios de taxi y limusina" },
  { en: "Technical and Vocational Training", pt: "Ensino técnico e profissionalizante", es: "Formación técnica y profesional" },
  { en: "Technology, Information and Internet", pt: "Tecnologia, Informação e Internet", es: "Tecnología, información e internet" },
  { en: "Technology, Information and Media", pt: "Tecnologia, Informação e Mídia", es: "Tecnología, información y medios" },
  { en: "Telecommunications", pt: "Telecomunicações", es: "Telecomunicaciones" },
  { en: "Telecommunications Carriers", pt: "Operadoras de Telecomunicações", es: "Operadores de telecomunicaciones" },
  { en: "Telephone Call Centers", pt: "Centros de Atendimento Telefônico", es: "Centros de atención telefónica" },
  { en: "Temporary Help Services", pt: "Trabalho temporário", es: "Trabajo temporal" },
  { en: "Textile Manufacturing", pt: "Fabricação de têxteis", es: "Fabricación de textiles" },
  { en: "Theater Companies", pt: "Companhias de Teatro", es: "Compañías de teatro" },
  { en: "Think Tanks", pt: "Centros de pesquisa", es: "Centros de investigación" },
  { en: "Tobacco Manufacturing", pt: "Fabricação de Tabaco", es: "Fabricación de tabaco" },
  { en: "Translation and Localization", pt: "Tradução e Localização", es: "Traducción y localización" },
  { en: "Transportation Equipment Manufacturing", pt: "Fabricação de Equipamentos de Transporte", es: "Fabricación de equipos de transporte" },
  { en: "Transportation Programs", pt: "Programas de Transporte", es: "Programas de transporte" },
  { en: "Transportation, Logistics, Supply Chain and Storage", pt: "Transporte, Logística, Cadeia de Suprimentos e Armazenamento", es: "Transporte, logística, cadena de suministro y almacenamiento" },
  { en: "Travel Arrangements", pt: "Organização de Viagens", es: "Organización de viajes" },
  { en: "Truck Transportation", pt: "Transporte rodoviário de cargas", es: "Transporte por camión" },
  { en: "Trusts and Estates", pt: "Fundos fiduciários e espólios", es: "Fideicomisos y sucesiones" },
  { en: "Turned Products and Fastener Manufacturing", pt: "Fabricação de Produtos Torneados e Fixadores", es: "Fabricación de productos torneados y elementos de fijación" },
  { en: "Urban Transit Services", pt: "Serviços de Trânsito Urbano", es: "Servicios de transporte urbano" },
  { en: "Utilities", pt: "Serviços de utilidade pública", es: "Servicios públicos" },
  { en: "Utilities Administration", pt: "Administração de serviços de utilidade pública", es: "Administración de servicios públicos" },
  { en: "Utility System Construction", pt: "Construção de sistemas de utilidade pública", es: "Construcción de sistemas de servicios públicos" },
  { en: "Vehicle Repair and Maintenance", pt: "Reparo e Manutenção de Veículos", es: "Reparación y mantenimiento de vehículos" },
  { en: "Venture Capital and Private Equity Principals", pt: "Capital de risco e private equity", es: "Capital de riesgo y capital privado" },
  { en: "Veterinary Services", pt: "Serviços Veterinários", es: "Servicios veterinarios" },
  { en: "Vocational Rehabilitation Services", pt: "Serviços de Reabilitação Profissional", es: "Servicios de rehabilitación profesional" },
  { en: "Warehousing and Storage", pt: "Armazenamento e Estocagem", es: "Almacenamiento" },
  { en: "Waste Collection", pt: "Coleta de Resíduos", es: "Recogida de residuos" },
  { en: "Waste Treatment and Disposal", pt: "Tratamento e Descarte de Resíduos", es: "Tratamiento y eliminación de residuos" },
  { en: "Water Supply and Irrigation Systems", pt: "Sistemas de Abastecimento de Água e Irrigação", es: "Sistemas de abastecimiento de agua y riego" },
  { en: "Water, Waste, Steam, and Air Conditioning Services", pt: "Serviços de Água, Resíduos, Vapor e Ar Condicionado", es: "Servicios de agua, residuos, vapor y aire acondicionado" },
  { en: "Wellness and Fitness Services", pt: "Serviços de Bem-estar e Fitness", es: "Servicios de bienestar y fitness" },
  { en: "Wholesale", pt: "Atacado", es: "Comercio mayorista" },
  { en: "Wholesale Alcoholic Beverages", pt: "Atacado de Bebidas Alcoólicas", es: "Comercio mayorista de bebidas alcohólicas" },
  { en: "Wholesale Apparel and Sewing Supplies", pt: "Atacado de vestuário e aviamentos", es: "Comercio mayorista de ropa y artículos de costura" },
  { en: "Wholesale Appliances, Electrical, and Electronics", pt: "Atacado de eletrodomésticos, elétricos e eletrônicos", es: "Comercio mayorista de electrodomésticos, eléctricos y electrónicos" },
  { en: "Wholesale Building Materials", pt: "Atacado de Materiais de Construção", es: "Comercio mayorista de materiales de construcción" },
  { en: "Wholesale Chemical and Allied Products", pt: "Atacado de Produtos Químicos e Afins", es: "Comercio mayorista de productos químicos y afines" },
  { en: "Wholesale Computer Equipment", pt: "Atacado de Equipamentos de Computador", es: "Comercio mayorista de equipos informáticos" },
  { en: "Wholesale Drugs and Sundries", pt: "Atacado de Medicamentos e Produtos Diversos", es: "Comercio mayorista de medicamentos y artículos diversos" },
  { en: "Wholesale Food and Beverage", pt: "Atacado de Alimentos e Bebidas", es: "Comercio mayorista de alimentos y bebidas" },
  { en: "Wholesale Footwear", pt: "Atacado de Calçados", es: "Comercio mayorista de calzado" },
  { en: "Wholesale Furniture and Home Furnishings", pt: "Atacado de Móveis e Artigos de Decoração", es: "Comercio mayorista de muebles y artículos para el hogar" },
  { en: "Wholesale Hardware, Plumbing, Heating Equipment", pt: "Atacado de ferragens, encanamento e aquecimento", es: "Comercio mayorista de ferretería, fontanería y calefacción" },
  { en: "Wholesale Import and Export", pt: "Atacado de Importação e Exportação", es: "Comercio mayorista de importación y exportación" },
  { en: "Wholesale Luxury Goods and Jewelry", pt: "Atacado de Artigos de Luxo e Jóias", es: "Comercio mayorista de artículos de lujo y joyería" },
  { en: "Wholesale Machinery", pt: "Atacado de Maquinário", es: "Comercio mayorista de maquinaria" },
  { en: "Wholesale Metals and Minerals", pt: "Atacado de Metais e Minerais", es: "Comercio mayorista de metales y minerales" },
  { en: "Wholesale Motor Vehicles and Parts", pt: "Atacado de Veículos e Peças", es: "Comercio mayorista de vehículos y piezas" },
  { en: "Wholesale Paper Products", pt: "Atacado de Produtos de Papel", es: "Comercio mayorista de productos de papel" },
  { en: "Wholesale Petroleum and Petroleum Products", pt: "Atacado de Petróleo e Produtos de Petróleo", es: "Comercio mayorista de petróleo y derivados" },
  { en: "Wholesale Photography Equipment and Supplies", pt: "Atacado de Equipamentos e Suprimentos de Fotografia", es: "Comercio mayorista de equipos y suministros de fotografía" },
  { en: "Wholesale Raw Farm Products", pt: "Atacado de Produtos Agrícolas Brutos", es: "Comercio mayorista de productos agrícolas sin procesar" },
  { en: "Wholesale Recyclable Materials", pt: "Atacado de Materiais Recicláveis", es: "Comercio mayorista de materiales reciclables" },
  { en: "Wind Electric Power Generation", pt: "Geração de Energia Elétrica Eólica", es: "Generación de energía eléctrica eólica" },
  { en: "Wineries", pt: "Vinícolas", es: "Bodegas" },
  { en: "Wireless Services", pt: "Serviços Sem Fio", es: "Servicios inalámbricos" },
  { en: "Women's Handbag Manufacturing", pt: "Fabricação de Bolsas Femininas", es: "Fabricación de bolsos de mujer" },
  { en: "Wood Product Manufacturing", pt: "Fabricação de Produtos de Madeira", es: "Fabricación de productos de madera" },
  { en: "Writing and Editing", pt: "Redação e Edição", es: "Redacción y edición" },
  { en: "Zoos and Botanical Gardens", pt: "Zoológicos e Jardins Botânicos", es: "Zoológicos y jardines botánicos" },
];
