import { sameTerm, type LocalizedTerm } from "./localized";

/** Practical technology suggestions. Product names stay the same in every language. */
export const TECHNOLOGY_SUGGESTIONS: readonly LocalizedTerm[] = [
  sameTerm("Amazon Web Services"),
  sameTerm("Angular"),
  sameTerm("Azure"),
  sameTerm("C#"),
  sameTerm("Docker"),
  sameTerm("DynamoDB"),
  sameTerm("Elasticsearch"),
  sameTerm("Fastify"),
  sameTerm("Git"),
  sameTerm("Go"),
  sameTerm("Google Cloud"),
  sameTerm("GraphQL"),
  sameTerm("Java"),
  sameTerm("JavaScript"),
  sameTerm("Kafka"),
  sameTerm("Kubernetes"),
  sameTerm("Laravel"),
  sameTerm("MongoDB"),
  sameTerm("MySQL"),
  sameTerm("NestJS"),
  sameTerm("Next.js"),
  sameTerm("Node.js"),
  sameTerm("PHP"),
  sameTerm("PostgreSQL"),
  sameTerm("Python"),
  sameTerm("React.js"),
  sameTerm("Redis"),
  sameTerm("Rust"),
  sameTerm("Svelte"),
  sameTerm("Tailwind CSS"),
  sameTerm("Terraform"),
  sameTerm("TypeScript"),
  sameTerm("Vue.js"),
];
